part of '../template_gallery_screen.dart';

const List<_TemplateCardModel> _templateCatalog = [
  _TemplateCardModel(
    label: 'Uptime Kuma',
    subtitle: 'Monitoring',
    description: 'Launch a hosted status page and uptime monitor in one click.',
    comparableTo: ['UptimeRobot'],
    name: 'uptime-kuma',
    image: 'louislam/uptime-kuma:latest',
    port: 3001,
    icon: Icons.monitor_heart_outlined,
    accent: Color(0xFF4CC9F0),
  ),
  _TemplateCardModel(
    label: 'Navidrome',
    subtitle: 'Music Server',
    description: 'Spin up a personal streaming library with ready-made data folders.',
    comparableTo: ['Spotify'],
    name: 'navidrome',
    image: 'deluan/navidrome:latest',
    port: 4533,
    icon: Icons.library_music_outlined,
    accent: Color(0xFFFFC857),
  ),
  _TemplateCardModel(
    label: 'Vaultwarden',
    subtitle: 'Passwords',
    description: 'Create a lightweight Bitwarden-compatible password server.',
    comparableTo: ['1Password'],
    name: 'vaultwarden',
    image: 'vaultwarden/server:latest',
    port: 80,
    icon: Icons.password_rounded,
    accent: Color(0xFF80ED99),
  ),
  _TemplateCardModel(
    label: 'Jellyfin',
    subtitle: 'Media',
    description: 'Stand up your own media server with persistent config storage.',
    comparableTo: ['Plex', 'Netflix'],
    name: 'jellyfin',
    image: 'jellyfin/jellyfin:latest',
    port: 8096,
    icon: Icons.movie_filter_outlined,
    accent: Color(0xFFFF7B72),
  ),
  _TemplateCardModel(
    label: 'Grafana',
    subtitle: 'Dashboards',
    description: 'Create a metrics dashboard stack with a single click.',
    comparableTo: ['Datadog'],
    name: 'grafana',
    image: 'grafana/grafana:latest',
    port: 3000,
    icon: Icons.insights_outlined,
    accent: Color(0xFFB388FF),
  ),
  _TemplateCardModel(
    label: 'Gitea',
    subtitle: 'Git Hosting',
    description: 'Deploy a self-hosted Git forge without touching Docker commands.',
    comparableTo: ['GitHub'],
    name: 'gitea',
    image: 'gitea/gitea:latest',
    port: 3000,
    icon: Icons.source_outlined,
    accent: Color(0xFF72DDF7),
  ),
  _TemplateCardModel(
    label: 'Nextcloud',
    subtitle: 'Files',
    description: 'Self-host a cloud drive alternative with persistent app storage.',
    comparableTo: ['Google Drive'],
    name: 'nextcloud',
    image: 'nextcloud:latest',
    port: 80,
    icon: Icons.cloud_outlined,
    accent: Color(0xFF8D99AE),
  ),
  _TemplateCardModel(
    label: 'Immich',
    subtitle: 'Photos',
    description: 'Run a self-hosted photo library with managed app data storage.',
    comparableTo: ['Google Photos'],
    name: 'immich-server',
    image: 'ghcr.io/immich-app/immich-server:release',
    port: 2283,
    icon: Icons.photo_library_outlined,
    accent: Color(0xFF7BDFF2),
  ),
  _TemplateCardModel(
    label: 'Outline',
    subtitle: 'Docs',
    description: 'Create a collaborative docs workspace similar to Notion.',
    comparableTo: ['Notion'],
    name: 'outline',
    image: 'outlinewiki/outline:latest',
    port: 3000,
    icon: Icons.edit_document,
    accent: Color(0xFFF7A072),
  ),
  _TemplateCardModel(
    label: 'Umami',
    subtitle: 'Analytics',
    description: 'Lightweight web analytics with a one-click launch flow.',
    comparableTo: ['Google Analytics'],
    name: 'umami',
    image: 'ghcr.io/umami-software/umami:latest',
    port: 3000,
    icon: Icons.query_stats_rounded,
    accent: Color(0xFFB8F2E6),
  ),
  _TemplateCardModel(
    label: 'Whoogle',
    subtitle: 'Search',
    description: 'Private metasearch front end with a simple managed service setup.',
    comparableTo: ['Google Search'],
    name: 'whoogle',
    image: 'benbusby/whoogle-search:latest',
    port: 5000,
    icon: Icons.travel_explore_rounded,
    accent: Color(0xFFA0C4FF),
    env: ['WHOOGLE_HTTP2=0'],
  ),
  _TemplateCardModel(
    label: 'Element',
    subtitle: 'Chat Client',
    description: 'Matrix web client with a dedicated config mount instead of the generic data layout.',
    comparableTo: ['Discord'],
    name: 'element',
    image: 'tiredofit/element:0.6.59',
    port: 80,
    icon: Icons.chat_bubble_outline_rounded,
    accent: Color(0xFF9D8DF1),
  ),
  _TemplateCardModel(
    label: 'Focalboard',
    subtitle: 'Projects',
    description: 'Kanban-style project management in a self-hosted service.',
    comparableTo: ['Trello'],
    name: 'focalboard',
    image: 'mattermost/focalboard:latest',
    port: 8000,
    icon: Icons.view_kanban_outlined,
    accent: Color(0xFFFFC6FF),
  ),
  _TemplateCardModel(
    label: 'Mattermost',
    subtitle: 'Chat',
    description: 'Team chat and collaboration with persistent local storage.',
    comparableTo: ['Slack'],
    name: 'mattermost',
    image: 'mattermost/mattermost-team-edition:latest',
    port: 8065,
    icon: Icons.forum_outlined,
    accent: Color(0xFF9BF6FF),
  ),
  _TemplateCardModel(
    label: 'NocoDB',
    subtitle: 'Database UI',
    description: 'Airtable-style interface for your data with a one-click setup.',
    comparableTo: ['Airtable'],
    name: 'nocodb',
    image: 'nocodb/nocodb:latest',
    port: 8080,
    icon: Icons.table_chart_outlined,
    accent: Color(0xFFFFD166),
  ),
  _TemplateCardModel(
    label: 'Adminer',
    subtitle: 'DB Viewer',
    description: 'Quick database inspection and management from a tiny container.',
    comparableTo: ['phpMyAdmin'],
    name: 'adminer',
    image: 'adminer:latest',
    port: 8080,
    icon: Icons.storage_outlined,
    accent: Color(0xFFBDE0FE),
  ),
  _TemplateCardModel(
    label: 'Test (nginx)',
    subtitle: 'Quick Check',
    description: 'Fastest way to confirm Docker, networking, and Serva are all working.',
    comparableTo: ['Hello world'],
    name: 'sovereignd-test',
    image: 'nginx:alpine',
    port: 80,
    icon: Icons.science_outlined,
    accent: Color(0xFF06D6A0),
  ),
];
